# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'StatesAndTerritories' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StatesAndTerritories 
  pod 'FontAwesome.swift'
  pod 'MBProgressHUD'
  pod 'PromiseKit'
  pod 'Sync'

  target 'StatesAndTerritoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StatesAndTerritoriesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

